#!/bin/sh
set -e

[ ! -e /usr/share/apache2/apache2-maintscript-helper ] ||
    . /usr/share/apache2/apache2-maintscript-helper

case "$1" in
    purge)
        # Remove config directory on purge
        rm -rf /etc/multiflexi-eu
        # Disable Apache configuration
        if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
            apache2_invoke disconf multiflexi-eu.conf || true
        fi
    ;;

    remove)
        if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
            apache2_invoke disconf multiflexi-eu.conf || true
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
